### ISSUE TITLE
Hide Preview Changes button

### ISSUE THREAD

**Issue by szepeviktor** [tlovett1/safe-redirect-manager#111]
Does this button function at all?

**Comment by inderpreet99** [comment]
I confirm it doesn't work.

There's no reason why it couldn't work for non-regex redirects. For regex ones, it would be tough to enumerate possible matching patterns. However, wildcard and non-wildcard (i.e. non-regex) redirects should be preview-able to show they work correctly.

**Comment by tlovett1** [comment]
PR to hide would be great.

**Comment by szepeviktor** [comment]
Would it be Ok for you to hide it by JavaScript or CSS?

`#preview-action`
