### ISSUE TITLE
Max limit 150?

### ISSUE THREAD

**Issue by danimalweb** [tlovett1/safe-redirect-manager#114]
Wondering why the max limit of redirects is set to 150?

Is this performance related? What are the impacts of having 300 loaded?

Thanks,

**Comment by tlovett1** [comment]
Yes, reason is performance related. It's more of a warning. You can certainly up that limit.

**Comment by danimalweb** [comment]
Ok, thanks. has much testing been done with > 150 up to 1000. What sort of performance issues are likely to occur?
