### ISSUE TITLE
Redirects do not work after 150 

### ISSUE THREAD

**Issue by milli05** [tlovett1/safe-redirect-manager#130]
If we add more than 150 redirects, only the most up to date 150 work, the ones created among the first ones do not.

**Comment by craiglondon** [comment]
There is a filter that you can use to override the 150.    But i am not sure how to use it.

I tried `add_filter( 'srm_max_redirects', 200 );` in my theme functions.php but that didn't seem to allow me to add another 50 re-directs.

**Comment by craiglondon** [comment]
I found the answer on the support forums on Wordpress.org
`add_filter( 'srm_max_redirects', 'dbx_srm_max_redirects' );
function dbx_srm_max_redirects() {
    return 250;
}'`

**Comment by milli05** [comment]
Thank you! I have tried it, and the filter overrides the
$this->default_max_redirects value, but there is still an error in the
get_redirects function, where the loop always stops before reading all the
redirects.
I create a pull request and see if it will be accepted.

2017-03-29 4:11 GMT+02:00 Craig London <notifications@github.com>:

**Comment by craiglondon** [comment]
@milli05 did you see my second comment?

**Comment by milli05** [comment]
I saw, yes thank you! I still sthink that sommething is wrong with the get_redirects function, there is a pull request already to fix it, see what will happen. :)
