### ISSUE TITLE
Quick Edit removed on all posts

### ISSUE THREAD

**Issue by jameswburke** [tlovett1/safe-redirect-manager#140]
[The quick edit removal code](https://github.com/tlovett1/safe-redirect-manager/blob/master/safe-redirect-manager.php#L86-L97) targets all post types, not just Safe Redirect Manger. Causes the quick edit button to be removed in all locations.

I have a PR I can submit to resolve this.

**Comment by tlovett1** [comment]
Fixed in 1.8
