### ISSUE TITLE
Extract redirect matching logic to its own match_redirect method.

### ISSUE THREAD

**Issue by nicholasio** [tlovett1/safe-redirect-manager#197]
**Is your enhancement related to a problem? Please describe.**

Recently on a client project, we had to "expand" internal redirected URLs. So we filtered a bunch of WordPress hooks to check if the URL had a redirect and if so we would output the redirected URL instead of the original URL.

**Describe the solution you'd like**

It would be way easier if we had a standalone method or function (something like `match_redirect( $url )` that would receive a URL and return the matched redirect or false if there is not a redirect. Then maybe_redirect (https://github.com/10up/safe-redirect-manager/blob/develop/inc/classes/class-srm-redirect.php#L58) would be refactored to use this method. The way the maybe_redirect method works is not easily testable and also does multiple things: matches the redirect and performs the redirect.

**Designs**

NA
**Describe alternatives you've considered**

I've tried to use the existing filter and constants (to short circuit the redirect) but the solution was ugly and very susceptible to break. I ended up copying the whole maybe_redirect method and making the changes I needed.

**Additional context**

**Comment by jeffpaul** [comment]
@nicholasio thanks for the feedback!  If you're able to work up a PR for this based on your effort so far, then we'd gladly get this through review and into an upcoming release.

**Comment by nicholasio** [comment]
@jeffpaul Just opened a PR for this: https://github.com/10up/safe-redirect-manager/pull/198

**Comment by nicholasio** [comment]
@jeffpaul I assume this can be closed now the #198 has been merged.
