### ISSUE TITLE
List unused redirects

### ISSUE THREAD

**Issue by scheinercc** [tlovett1/safe-redirect-manager#199]
**Is your enhancement related to a problem? Please describe.**

The number of redirects can grow quite big over time on a large site.

**Describe the solution you'd like**

Old redirects might not be hit anymore. The idea suggested is to e.g. add a timestamp when a redirect got hit and list the once which didn't get hit for 12 months or more.

**Designs**

A new table linked in the list above "All (xx) | Mine (xx) | ... Draft (xx) | **Unused (xx)**"

**Describe alternatives you've considered**

Could just be a new column in the "All" table named "Last Used" where the once fulfilling the rule get marked red.

**Additional context**

Creating a separate table makes it easier to add descriptive content.

**Comment by jeffpaul** [comment]
@scheinercc welcome to Safe Redirect Manager and thanks for the feedback!  This seems like a decent use case to consider and if you're able to work up a PR then I'd gladly get that to the team for review so that this ships in an upcoming release.

**Comment by TheLastCicada** [comment]
I'm generally against this type of feature as it allows writes to the database based on user visits.  Database writes do not scale well and you are opening a vector for a denial of service attack on a site by allowing anyone to create a write to the database simply by making a request to a redirected page.  This could be implemented safely by storing the log of redirect hits to a cache like memcache if enabled, or into a log file, but generally making a write to MySQL based on a user visiting a URL on your site will lead to downtime.

**Comment by jeffpaul** [comment]
Thanks for the insight @TheLastCicada, I'm going to close this accordingly but if there's a hook that would help someone store those redirect hits to a cache or log file then please re-open/comment and we can address that way.
