### ISSUE TITLE
Add 410 Gone Support

### ISSUE THREAD

**Issue by PopVeKind** [tlovett1/safe-redirect-manager#205]
**Is your enhancement related to a problem? Please describe.**

_Google **previously** processed 404 Errors and 410 Errors identically. This frequently left many 404s on URLs that were in the crawl list, the index, and listed as 404 Errors in Google Search Console. Google now uses 404s as a factor in website ranking and domain delisting._

Currently, the `410` code has been changed at Google to this behavior:

1. ASAP Remove URL from the crawl list. (`404` does **_not_** do this)
2. ASAP Remove URL from the Index. (`404` does **_not_** do this)
3. Stop crawling the URL (unless a link to it is found again) (`404` continues to crawl the URL for _up to a year_, wasting Google's bandwidth - and yours too!).
4. A `410` for a short time, **_after a 301_** is removed, will prevent `404s `in _Google Search Console_. 

**Describe the solution you'd like**

Add a `410 Gone` Selection in the dropdown with the `404 Not Found`

**Designs**

Copy the code for `404 Not Found` and modify it to `410 Gone`

**Describe alternatives you've considered**

- I was able to do this with the much heavier [Redirection Plugin](https://wordpress.org/plugins/redirection/) on any platform.

- I was able to do this using .htaccess on Apache from [Pair Networks](https://www.pair.com/).

- I am now teaching Newbies to use a Linode - Ubuntu - [WordOps](https://wordops.net/) - Nginx + MariaDB - WordPress + [YOURLS](https://yourls.org/)  - Which is easier, faster, and has fewer problems than the Apache install mentioned. Of course, it also includes the YOURLS URL Shortener!

- I hope to include the _Safe Redirect Manager_ so that Noobs working on both Apache **_and_** Nginx can easily set up `301s` and `410s` with one lightweight plugin.

**Additional context**

**_Two examples of how it should work:_**

**First Assume:** _Google Search Console_ reports a 404 Error that has no links to it and is not used/needed. Such as a test page or a coming event page that has past and was deleted.

- Step 1 - Set up a `410 Gone` for that URL.

- Step 2 - _Google Search Console_ deletes the `404 Not Found` and now reports a `410 Gone`, (within a week or so, or use _Google Search Console_ to recrawl the URL).

- Step 3 - Remove the `410 Gone` for that URL.

**First Results:** Both `404` and `410` are removed from _Google Search Console_.

**Second Assume:** You wish to remove a page from your website.

- Step 1 - Set up a `301` for that URL to a new page with new info.

- Step 2 - Work to remove any links to that page. For a test page, this may take minutes. Or it may take months for a popular page (perhaps you should rebuild and republish popular URLs?)

- Step 3 - Set up a `410 Gone` for that URL.

- Step 4 - The `410 Gone` will appear in your _Google Search Console_.

- Step 5 - Remove the `410 Gone` for that URL.

**Second Results:** When you remove the `301` there is no `404` in your _Google Search Console_.

**Conclusions:**

_This should be useful in an SEO Strategy as many `404` URLs in the crawl list have proven to depreciate a site._

Persons who type in a faulty URL will still receive a 404. For this, I would suggest a custom 404 page, to lead them back into your site.

**Comment by jeffpaul** [comment]
@PopVeKind thanks for the well documented enhancement request, that's very much appreciated.  Adding this support seems worthwhile, would you be up for crafting a PR to support this issue?

**Comment by jeffpaul** [comment]
@PopVeKind checking in to see how your testing/usage of this is going now that it was released in version 1.10.1 last month?

**Comment by aosmichenko** [comment]
This doesn't work plugin is hitting this wall on all status codes higher than 399 
https://core.trac.wordpress.org/browser/branches/5.7/src/wp-includes/pluggable.php#L1307

**Comment by dinhtungdu** [comment]
@aosmichenko Thanks for your report, look like we can't do anything in this case. Going to remove the 410 status code.

**Comment by aosmichenko** [comment]
@dinhtungdu I would make a custom response in case of 400+ check my PR
