### ISSUE TITLE
Loop detection

### ISSUE THREAD

**Issue by noesteijver** [tlovett1/safe-redirect-manager#206]
Hello,

We’ve added the loop detection code as mentioned here:

https://github.com/10up/safe-redirect-manager#redirect-loops

What kind of loops should this detect/prevent?

For example, the situation below still gives an error:

Redirect from /page-1/ to http://website.com/page-2/ and
redirect from /page-2/ to http://website.com/page-1/

(when there are many redirects, this might happen)

Hope to hear from you, thanks in advance!
-Kevin

**Comment by dinhtungdu** [comment]
Hi @noesteijver, I checked the doc and realized that it's incorrect. I'm sorry about that. The correct code snippet to enable loop detection is:

```
add_filter( 'srm_check_for_possible_redirect_loops', '__return_true' );
```

I tested the snippet above and the plugin can detect the redirect loop. See the screenshot below:

<img width="622" alt="Screenshot at May 07 10-16-53" src="https://user-images.githubusercontent.com/5423135/81251164-d98c8280-904c-11ea-90db-c66ed4599348.png">

We will update the docs to correct this info. Thank you for reporting this issue!
