### ISSUE TITLE
Redirect Rule Admin Search & ElasticPress

### ISSUE THREAD

**Issue by rickalee** [tlovett1/safe-redirect-manager#225]
When ElasticPress and Safe Redirect Manager are used together it does not successfully search the _redirect_rule_from and _redirect_rule_to meta fields for redirect_rule.

wp-admin/edit.php?s=project&post_status=all&post_type=redirect_rule

**Comment by sultann** [comment]
Hi @rickalee, could you check if the issue still exists? In my testing, it's working fine.
