### ISSUE TITLE
$parsed_requested_path['path'] doesn't always exits

### ISSUE THREAD

**Issue by davidmondok** [tlovett1/safe-redirect-manager#244]
**Describe the bug**

Our debug log is flooded with undefined index warnings `Undefined index: path in /.../plugins/safe-redirect-manager/inc/classes/class-srm-redirect.php on line 121`.

It's usually several warnings that are logged in a matter of seconds. Maybe it happens when WP-Rocket is preloading URLs, but this is just a very vague assumption.

There used to be a check for this but it was removed in #196 under the assumption that `$parsed_requested_path['path']` always exists which isn't the case unfortunately. We would suggest to reimplement the check to avoid this warning.

**Environment information**

`
### wp-core ###

version: 5.7.2
site_language: de_DE
user_language: de_DE
timezone: Europe/Vienna
permalink: /blog/%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 85566
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/1000things/prod-v2/releases/20/web/wp
wordpress_size: loading...
uploads_path: /var/www/1000things/prod-v2/releases/20/web/app/uploads
uploads_size: loading...
themes_path: /var/www/1000things/prod-v2/releases/20/web/app/themes
themes_size: loading...
plugins_path: /var/www/1000things/prod-v2/releases/20/web/app/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: 1000things (1000things)
version: 1.0.0
author: Woda
author_website: https://www.woda.at
parent_theme: none
theme_features: menus, disable-colors, disable-custom-colors, disable-font-sizes, disable-custom-font-sizes, disable-gradients, disable-custom-gradients, editor-styles, responsive-embeds, custom-units, editor-color-palette, editor-font-sizes, editor-gradient-presets, post-formats, post-thumbnails, custom-background, custom-header, custom-logo, automatic-feed-links, html5, title-tag, customize-selective-refresh-widgets
theme_path: /var/www/1000things/prod-v2/releases/20/web/app/themes/1000things

### wp-themes-inactive (11) ###

Twenty Eleven: version: 3.7, author: the WordPress team
Twenty Fifteen: version: 2.9, author: the WordPress team
Twenty Fourteen: version: 3.1, author: the WordPress team
Twenty Nineteen: version: 2.0, author: the WordPress team
Twenty Seventeen: version: 2.7, author: the WordPress team
Twenty Sixteen: version: 2.4, author: the WordPress team
Twenty Ten: version: 3.3, author: the WordPress team
Twenty Thirteen: version: 3.3, author: the WordPress team
Twenty Twelve: version: 3.3, author: the WordPress team
Twenty Twenty: version: 1.7, author: the WordPress team
Twenty Twenty-One: version: 1.3, author: the WordPress team

### wp-mu-plugins (6) ###

Bedrock Autoloader: version: 1.0.1, author: Roots
Disallow Indexing: version: 1.0.0, author: Roots
Disallow WP Rocket WP_CACHE constant: version: 1.0.0, author: Woda
Register Theme Directory: version: 1.0.0, author: Roots
WP-Rocket commands for WP-CLI: version: 1.0.0, author: Woda
WP-Rocket disable generating advanced-cache: version: 1.0.0, author: Woda

### wp-plugins-active (45) ###

Admin Columns Pro: version: 5.5.3, author: AdminColumns.com
Admin Columns Pro - Yoast SEO: version: 1.0.3, author: AdminColumns.com
Advanced Custom Fields: Ninjaforms Add-on: version: 1.1, author: Danny van Holten
Advanced Custom Fields PRO: version: 5.9.7, author: Elliot Condon
Avatar Privacy: version: 2.5.2, author: Peter Putzer
Better Notifications for WP: version: 1.8.6, author: Made with Fuel
Borlabs Cookie - Cookie Opt-in: version: 2.2.28, author: Benjamin A. Bornschein, Borlabs
bunny.net: version: 1.0.8, author: bunny.net
Carbon Fields: version: 3.3.0, author: htmlburger
Clean Image Filenames: version: 1.3, author: Upperdog
Disable Comments: version: 2.1.2, author: WPDeveloper
Disable Emojis (GDPR friendly): version: 1.7.2, author: Ryan Hellyer
Edit Author Slug: version: 1.8.2, author: Brandon Allen
Email Encoder - Protect Email Addresses: version: 2.1.1, author: Ironikus
Enable Media Replace: version: 3.5.0, author: ShortPixel
Login Designer: version: 1.2.5, author: Rich Tabor
Login No Captcha reCAPTCHA (Google): version: 1.6.11, author: Robert Peake and Contributors
Nextend Social Login: version: 3.0.28, author: Nextendweb
Nextend Social Login Pro Addon: version: 3.0.28, author: Nextendweb
Ninja Forms: version: 3.5.5, author: Saturday Drive
oEmbed Plus: version: 1.6, author: Ayesh Karunaratne
Pinpoll: version: 4.0.0, author: Pinpoll
PublishPress Authors Pro: version: 3.14.0, author: PublishPress
PublishPress Capabilities Pro: version: 2.0.3, author: PublishPress (latest version: 2.1)
PublishPress Pro: version: 3.3.3, author: PublishPress
Regenerate Thumbnails Advanced: version: 2.4.0, author: ShortPixel
Relevanssi Premium: version: 2.14.4, author: Mikko Saari
Remove Dashboard Access: version: 1.1.3, author: Drew Jaynes (DrewAPicture)
Rewrite Rules Inspector: version: 1.3.1, author: Automattic, Daniel Bachhuber
Safe Redirect Manager: version: 1.10.0, author: 10up
Safe SVG: version: 1.9.9, author: Daryll Doyle
Scheduled Post Trigger: version: 3.0, author: Jennifer Moss - Moss Web Works
Search & Filter Pro: version: 2.5.8, author: Code Amp (latest version: 2.5.9)
User Login History: version: 2.1.0, author: Er Faiyaz Alam
User Switching: version: 1.5.7, author: John Blackbourn & contributors
Woda Dynamic Content Manager: version: 0.3.0, author: Woda
WP-Cron Status Checker: version: 1.2.2, author: Webhead LLC
WP Better Emails: version: 0.4, author: Nicolas Lemoine
WP Crontrol: version: 1.10.0, author: John Blackbourn & crontributors
WP Mail SMTP: version: 2.8.0, author: WPForms (latest version: 2.9.0)
WP Rocket: version: 3.8.8, author: WP Media (latest version: 3.9.0.4)
WP Rocket | Add custom htaccess rules: author: WP Rocket Support Team, version: (undefined)
Yet Another Related Posts Plugin (YARPP): version: 5.25.0, author: YARPP
Yoast Duplicate Post: version: 4.1.2, author: Enrico Battocchi & Team Yoast
Yoast SEO: version: 16.5, author: Team Yoast (latest version: 16.6)

### wp-plugins-inactive (14) ###

Ninja Forms - Layout & Styles: version: 3.0.29, author: The WP Ninjas
Ninja Forms - User Management: version: 3.0.11, author: WP Ninjas
Peter's Login Redirect: version: 2.9.9, author: Peter Keung
Pods - Custom Content Types and Fields: version: 2.7.28, author: Pods Framework Team
PublishPress Checklists Pro: version: 2.6.0, author: PublishPress
Query Monitor: version: 3.7.1, author: John Blackbourn
Restricted Site Access: version: 7.2.0, author: Jake Goldman, 10up, Oomph
Rollbar: version: 2.6.1, author: Rollbar
Schema Pro: version: 2.6.1, author: Brainstorm Force
ShortPixel Adaptive Images: version: 2.3.0, author: ShortPixel (latest version: 2.3.1)
ShortPixel Image Optimizer: version: 4.22.2, author: ShortPixel
Simple Local Avatars: version: 2.2.0, author: Jake Goldman, 10up
Sucuri Security - Auditing, Malware Scanner and Hardening: version: 1.8.26, author: Sucuri Inc.
Yoast Test Helper: version: 1.14, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Nicht verfügbar
imagemagick_version: Nicht verfügbar
file_uploads: File uploads is turned off
post_max_size: 50M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
gd_version: 2.2.5
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.19.0-17-amd64 x86_64
httpd_software: Apache
php_version: 7.4.20 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 300
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 50M
php_post_max_size: 50M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.4.20-MariaDB-1:10.4.20+maria~buster
client_version: mysqlnd 7.4.20

### wp-constants ###

WP_HOME: https://www.1000things.at
WP_SITEURL: https://www.1000things.at/wp
WP_CONTENT_DIR: /var/www/1000things/prod-v2/releases/20/web/app
WP_PLUGIN_DIR: /var/www/1000things/prod-v2/releases/20/web/app/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: ./wp-errors.log
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### publishpress-modules (20) ###

modules_settings: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/modules_settings]
calendar: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/calendar]
editorial_metadata: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/editorial_metadata]
content_overview: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/content_overview]
custom_status: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/custom_status]
notifications: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/notifications]
improved_notifications: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/improved_notifications]
async_notifications: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/async_notifications]
notifications_log: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/notifications_log]
roles: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/roles]
user_groups: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/user_groups]
dashboard: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/dashboard]
editorial_comments: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/editorial_comments]
settings: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/settings]
efmigration: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/efmigration]
debug: off [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/modules/debug]
prosettings: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/modules/prosettings]
slack: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/modules/slack]
reminders: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/modules/reminders]
notifynetworkadmin: on [/var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/modules/notifynetworkadmin]

### publishpress ###

PUBLISHPRESS_VERSION: 3.3.3
PUBLISHPRESS_BASE_PATH: /var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress
PUBLISHPRESS_FILE_PATH: /var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/publishpress.php
PUBLISHPRESS_URL: https://www.1000things.at/app/plugins/publishpress-pro/vendor/publishpress/publishpress/
PUBLISHPRESS_SETTINGS_PAGE: https://www.1000things.at/wp/wp-admin/admin.php?page=pp-modules-settings&module=pp-modules-settings-settings
PUBLISHPRESS_LIBRARIES_PATH: /var/www/1000things/prod-v2/releases/20/web/app/plugins/publishpress-pro/vendor/publishpress/publishpress/libraries
WP_CONTENT_DIR: /var/www/1000things/prod-v2/releases/20/web/app
WP_CONTENT_URL: https://www.1000things.at/app
option::date_format: j. F Y
option::time_format: G:i
option::timezone_string: Europe/Vienna
option::gmt_offset: 2
php::date_default_timezone_get: UTC

### wp_mail_smtp ###

version: 2.8.0
license_key_type: lite
debug: No debug notices found.
db_tables: 1000things_wpmailsmtp_tasks_meta
lite_install_date: Sep 9, 2020 @ 9:23pm

`

**Additional context**

**Comment by jeffpaul** [comment]
@davidmondok welcome to Safe Redirect Manager and thanks for the feedback!  I've milestoned this for the next major release and will welcome any further triage or associated PR to resolve this.

**Comment by dinhtungdu** [comment]
@davidmondok Thanks for the PR, I reverted the change from @braders (which I suggested removing). Can you please test #246 to see if it fixes your issue?

**Comment by davidmondok** [comment]
@dinhtungdu I removed line 127 (I just created a PR) to make it work, because that's the line that had to be moved into an if statement. But other than that, the fix worked for me. No more errors in our log. Thanks a lot.

**Comment by dinhtungdu** [comment]
Thanks for the head-up @davidmondok! I merged your PR into the main one.
