### ISSUE TITLE
PHP notice in SRM_Redirect::match_redirect() for paths with multiple leading slashes

### ISSUE THREAD

**Issue by ocean90** [tlovett1/safe-redirect-manager#256]
**Describe the bug**
I noticed the following PHP notice in the logs:

>  Trying to access array offset on value of type bool in plugins/safe-redirect-manager/inc/classes/class-srm-redirect.php on line 126

This notice is caused by accessing a site with kind of a broken path like `example.com///someting/`. In this case `wp_parse_url()` (and `parse_url()`) return false for the path in https://github.com/10up/safe-redirect-manager/blob/285d8eec1d93f175dba6bdce0670f4e984631c81/inc/classes/class-srm-redirect.php#L110-L114

**Steps to Reproduce**
1. Activate the plugin
2. Enable debug mode to ensure the notices are logged
3. Open `example.com///someting/` in the browser where example.com is the URL of your site
4. See the notice in the logs

**Expected behavior**
No PHP notice.

**Additional context**
These are the results of `wp_parse_url()` for different path values:

```
# All good.
wp> wp_parse_url( '/foo/' );
=> array(1) {
  ["path"]=>
  string(5) "/foo/"
}

# No notice but also not good.
wp> wp_parse_url( '//foo/' );
=> array(2) {
  ["host"]=>
  string(3) "foo"
  ["path"]=>
  string(1) "/"
}

# We broke it.
wp> wp_parse_url( '///foo/' );
=> bool(false)
```

**Possible solutions**

* Bail early if `$parsed_requested_path` is false
* Replace `wp_parse_url()` with something like `strtok( $normalized_requested_path, '?' );` to separate the path and query
* In `$normalized_requested_path` merge multiple slashes into one
* Fallback to `$normalized_requested_path` if `$parsed_requested_path` is false

**Comment by rahulsprajapati** [comment]
Hello @ocean90, 👋

Thank you for the detailed information on this issue. 

Looks like this issue is related to https://github.com/10up/safe-redirect-manager/issues/244 and it fixed with https://github.com/10up/safe-redirect-manager/pull/246 

Would you mind checking the latest code from develop and confirm if this fixes for you? 

We should have this fix in next release.

**Comment by ocean90** [comment]
Thanks for the hint, #246 does fix this indeed.
