### ISSUE TITLE
Test against WordPress 5.9

### ISSUE THREAD

**Issue by sudip-md** [tlovett1/safe-redirect-manager#258]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

- [ ]  test WP New Relic on WordPress 5.9
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ]  bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
None

**Additional context**

**Comment by sudip-md** [comment]
I have tested this plugin in WordPress 5.9 version and it is working fine.

WP version : 5.9
Plugin version : 1.10.0
CC: @ankitguptaindia @jeffpaul

**Comment by ankitguptaindia** [comment]
@jeffpaul This Plugin is ready for a WP 5.9 Compatibility Version Bump update. Thank you!
