### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [tlovett1/safe-redirect-manager#267]
Is your enhancement related to a problem? Please describe.
Once WordPress 6.0 is released, we'll want to test Safe Redirect Manager to see if any incompatibility issues arise.

Describe the solution you'd like

- [x] test Safe Redirect Manager on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

Designs
n/a

Describe alternatives you've considered
none

Additional context
Related: #258, #245, #232, #227, #204

**Comment by peterwilsoncc** [comment]
While testing this against 6.0, I've created https://github.com/10up/safe-redirect-manager/issues/269

Testing against older versions of WP, it appears to have been around for a while so I think this is safe to bump to inidicate 6.0 support. I'll create a pull request.
