### ISSUE TITLE
Regex redirects without leading `/` are buggy

### ISSUE THREAD

**Issue by peterwilsoncc** [tlovett1/safe-redirect-manager#269]
### Describe the bug

Enabling a regular expression without a leading `/` can be quite buggy.

* in most cases I am getting redirected to the wp-admin
* if a full URL is added added as the destination, it will include the domain twice.

### Steps to Reproduce

Scenario One

1. Create a regular expression redirect
    - Redirect from: `(go|be)\/h{0,}$`
    - Redirect to: `/404-regex`
2. In the CLI run `curl -I http://xu-osp-plugins.local/be/hhhh`
3. Observe the location header is `http://xu-osp-plugins.local/wp-admin/`

Scenario Two

1. Create a regular expression redirect
    - Redirect from: `(go|be)\/h{0,}$`
    - Redirect to: `http://xu-osp-plugins.local/404-regex`
2. In the CLI run `curl -I http://xu-osp-plugins.local/be/hhhh`
3. Observe the location header is `/http://xu-osp-plugins.local/wp-admin/` (note leading slash)

### Environment information

- Device MacBook Pro
- OS: MacOs 11.6.5
- Browser: curl 7.64.1 

### WordPress information

WordPress 6.0
WordPress 5.9
WordPress 5.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@peterwilsoncc do you think it's noting the WP site URL ahead of the input field including a trailing `/` and then strip any leading `/` in the input field?

**Comment by peterwilsoncc** [comment]
@jeffpaul Let me consider it for a bit.

I'll do some further tests with the code @iamdharmesh left commented out in 4c0421886b26d189de7f298ebd279d20e386e917 and see if there are further edge cases for regexes starting with `^` or `^/`.
