### ISSUE TITLE
Deprecated function and possible slow_db_query_meta_value

### ISSUE THREAD

**Issue by ldanielgiuliani** [tlovett1/safe-redirect-manager#287]
### Describe your question

https://wordpress.org/support/topic/deprecated-function-and-possible-slow_db_query_meta_value/#post-16107993

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ravinderk** [comment]
This issue is already fixed in https://github.com/10up/safe-redirect-manager/pull/322. Please update to the latest add-on and let us know if you can reproduce the issue.
