### ISSUE TITLE
Deprecated action requirements prevent merging.

### ISSUE THREAD

**Issue by peterwilsoncc** [tlovett1/safe-redirect-manager#304]
### Describe the bug

When the minimum PHP version was updated to 7.4, earlier versions were removed from the PHP Unit matrix for testing.

Reviewing https://github.com/10up/safe-redirect-manager/pull/302, it appears the repo's settings of required actions were not updated to remove the unsupported PHP versions.

These settings will need to be updated to allow non-admins to merge.

### Steps to Reproduce

1. Go to https://github.com/10up/safe-redirect-manager/pull/302
2. Review the required actions above the merge button
3. Observe the requirements for PHP 5.6 - 7.3
4. On the PR's checks tab, observe these actions no longer exist.

### Screenshots, screen recording, code snippet

![Screen Shot 2023-01-30 at 10 44 59 am](https://user-images.githubusercontent.com/519727/215362830-2fb56e0a-8ea7-499f-aa97-9a88a6b66778.png)

### Environment information

GitHub actions

### WordPress information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@peterwilsoncc this should be resolved now, please confirm & close if you concur... thanks!

**Comment by peterwilsoncc** [comment]
LGTM based on existing open PRs, thank you!
