### ISSUE TITLE
Undefined index 'message'

### ISSUE THREAD

**Issue by vena** [tlovett1/safe-redirect-manager#320]
Looks like a message field was added a while back

https://github.com/10up/safe-redirect-manager/blob/ae20aa5e08ee4e88f0dcade30492169aca282c60/inc/classes/class-srm-redirect.php#L144

Existing redirects from before this change don't seem to have that, so they generate a notice when you attempt to access it. Small thing, only happened to notice on a dev instance with error display on.

**Comment by dkotter** [comment]
Thanks for the report @vena. We have a PR up already to address this: https://github.com/10up/safe-redirect-manager/pull/319. If you have time to test and verify that PR addresses your issue, that would be helpful.

**Comment by vena** [comment]
ah, checked existing issues, didn't see the PR. that'll do it!
