### ISSUE TITLE
Redirect.js can leave publish button disabled when fields are valid

### ISSUE THREAD

**Issue by peterwilsoncc** [tlovett1/safe-redirect-manager#366]
### Describe the bug

As the redirect.js file uses the `change` event to detect whether fields are valid, it requires users click out of the box before detecting the field has been filled out.

This can lead to confusion as the publish button remains disabled when the redirect fields have valid data, the user needs to click out of the field and then click the publish button.

This was reported in https://github.com/10up/safe-redirect-manager/issues/364#issuecomment-1939361111 (props @JosVelasco).

### Steps to Reproduce

1. Change the redirect status code to `301`
2. Click in to the redirect from to field
3. Type then delete some text
4. Click out of the redirect from field
5. The publish button should be disabled
6. Click in to the redirect from field
7. Type something, do NOT click out of the box
8. The publish button will remain disabled.

### Environment information

- Device: Macbook
- Browser: Firefox 122/macOS 12.7.3 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BhargavBhandari90** [comment]
Hi Plugin Author,

I would like to work on this issue.
