### ISSUE TITLE
Add Screenshots for `.org`

### ISSUE THREAD

**Issue by faisal-alvi** [tlovett1/safe-redirect-manager#390]
### Is your enhancement related to a problem? Please describe.

The [Safe Redirect Manager plugin on ORG](https://wordpress.org/plugins/safe-redirect-manager/) currently lacks screenshots showcasing its functionality and settings pages. Screenshots should be added, along with a GIF demonstrating the Bulk Edit feature, as discussed [here](https://github.com/10up/safe-redirect-manager/pull/350#issuecomment-2288699657).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@faisal-alvi as we're looking to ship v2.2.0 shortly, could you work on crafting these screenshot/cast additions?
