### ISSUE TITLE
Redirection to HTTPS

### ISSUE THREAD

**Issue by tlovett1** [tlovett1/safe-redirect-manager#46]
It would be super useful to me if this plugin could handle redirecting http to https for certain URL's. Thoughts on this @danielbachhuber ?

**Comment by benoitchantre** [comment]
Chrome 62 is coming soon and will display a _Not Secured_ warning for all pages served over http. Users should check and update their redirects.

The next update of this plugin could display an admin notice if there are http redirects and eventually provide a link to convert all redirects to https automatically.
