### ISSUE TITLE
Check redirect targets

### ISSUE THREAD

**Issue by szepeviktor** [tlovett1/Safe-Redirect-Manager#73]
It would be nice to check the target whether it is an existing permalink.

**Comment by szepeviktor** [comment]
...providing it is an internal URL.

**Comment by tlovett1** [comment]
What are you thinking should happen if it is an internal link?

**Comment by szepeviktor** [comment]
Run through WP query and display a notice that is a broken link.

**Comment by tlovett1** [comment]
I think this is out of scope of the plugin.

**Comment by szepeviktor** [comment]
Could you give me a hint how to hook SRM to accomplish this?
