### ISSUE TITLE
Feature request: add redirect from post/page/custom post type

### ISSUE THREAD

**Issue by Willem-Siebe** [tlovett1/Safe-Redirect-Manager#81]
Hi,

Would love to have an option like this on my edit screens for post/pages/custom post types:

![2015-02-26_10-38-12](https://cloud.githubusercontent.com/assets/5107354/6389646/1fa3e882-bda6-11e4-8659-353026242afe.jpg)

**Comment by tlovett1** [comment]
Appreciate the suggestion!

**Comment by Willem-Siebe** [comment]
Is it maybe an idea to only allow this for custom post types. When I'm right WordPress already does 301 redirects automatically when you change post/page permalinks. Is that WordPress 100% error proof, because we don't have a overview of the 301 redirects which is pretty annoying.

**Comment by tlovett1** [comment]
Having trouble following your last comment :/

**Comment by Willem-Siebe** [comment]
Hi, well I've tried to finds some documentation about it since I have seen a place where it was explained, can't find it anymore, so I have looked at Github of WordPress myself.

My feature request was/is to add a box to posts/pages/custom post types, so when I change a permalink to a new permalink I can easily add this 301 redirect into Safe Redirect Manager using that box instead of going to the admin screen of your plugin.

But then I remembered: when I change a permalink of a post and page, WordPress always finds the new Permalinks, also when I use the old one > which means that wordpress is doing the redirect for us already. This is what I found in WP:

- https://github.com/WordPress/WordPress/blob/7dcb041d5a9e6b296250d6c2ad9e7bd269607235/wp-includes/query.php#L4648-L4707
- https://github.com/WordPress/WordPress/blob/612b9e8ffde4687b46f4733afd0dc95963388804/wp-includes/canonical.php

So hopefully you understand my last comments, because when this 301 redirect of WP is 100% error proof, it makes no sense to add this kind of box to posts/pages and do it manually again while WordPress is also doing it automatically.

Curious to your opinion about this.

**Comment by Willem-Siebe** [comment]
Hi, was my explenation clear now about the auto-301-redirect that WP is already having in their code?

**Comment by tlovett1** [comment]
Yes, if you change a permalink, WordPress auto handles the redirect for you. I __think__ if you change it multiple times it only remembers the last redirect.

**Comment by Willem-Siebe** [comment]
Hi there, did some testing with pages, posts and WooCommerce products.

The 301 redirects build-in in WordPress are not 100% error proof!

When I change a permalink (product/post/page) from orginal `/hi-there/` to `/there-hi/` WordPress is NOT saving this redirect. 

WordPress redirects only seem to handle simple changes from `/hi-there/` to `/hi-there1/` for example. And when I change `/hi-there1/` to `/hi-there2/`, is not resulting in 2 redirect but in one from original `/hi-there/` to `/hi-there2/`. So this feature in WP can no be trusted and the more important is a good plugin like yours to manage 301 redirects everytime I change a permalink.

This being researched and said: when I change a permalink from a post/page/product or any other CPT it would be way more easier if I can add a redirect into safe redirect manager when staying on the same page > see my original feature request :-).

Are you taking this in consideration and if yes, do you maybe have a timeline?
